[Unit]
# non-boot-blocking condition to wait for /secure to be mounted before starting the service
{% if pillar['secure-is-a-mount']%}
ConditionPathIsMountPoint=/secure
{% endif %}
After=secure.mount
StartLimitIntervalSec=0


[Service]
Restart=on-failure
RestartSec=30s
