#cloud-config
groups:
    - salt


users:
    - name: salt
      primary_group: salt
      shell: /usr/sbin/nologin
      homedir: /opt/saltstack/salt


write_files:
    - path: /etc/salt/minion.d/saltshaker.conf
      content: |
          master: ${hcloud_servers.servers['saltmaster'].ipv4_address}
          hash_type: sha256
          log_level: debug
          #log_file: /dev/log
          state_verbose: false
          mine_interval: 5


runcmd:
    - mkdir -p /etc/apt/keyrings
    - wget -O /etc/apt/keyrings/salt-archive-keyring-2023.gpg https://repo.saltproject.io/salt/py3/debian/12/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
    - sh -c 'echo deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/debian/12/amd64/latest bookworm main > /etc/apt/sources.list.d/salt.list'
    - apt update
    - mkdir -p /etc/salt/roles.d
%{ for role in roles ~}
    - touch /etc/salt/roles.d/${role}
%{ endfor ~}
%{ if ipv6_only ~}
    - echo true > /etc/salt/env.d/ipv6_only
%{ endif ~}
    - mkdir /run/salt-bootstrap
    - wget -O /run/salt-bootstrap/bootstrap-salt.sh https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
    - chown -R salt:salt /etc/salt
    - chmod 700 /run/salt-bootstrap/bootstrap-salt.sh
    - /usr/bin/bash /run/salt-bootstrap/bootstrap-salt.sh -r -x python3 -M


final_message: |
    Next steps:
        Add the minion key on saltmaster. Execute highstate:
            salt-key -y -a ${hostname}
            salt '${hostname}' state.highstate