#cloud-config
groups:
    - salt


users:
    - name: salt
      primary_group: salt
      shell: /usr/sbin/nologin
      homedir: /opt/saltstack/salt


write_files:
    - path: /etc/salt/master.d/saltshaker.conf
      content: |
          ${indent(10, saltmaster_config)}
    - path: /etc/salt/minion.d/saltshaker.conf
      content: |
          master: 127.0.0.1
          hash_type: sha256
          log_level: debug
          #log_file: /dev/log
          state_verbose: false
          mine_interval: 5


runcmd:
    - mkdir -p /etc/apt/keyrings
    - /usr/bin/wget -O /etc/apt/keyrings/salt-archive-keyring-2023.gpg https://repo.saltproject.io/salt/py3/debian/12/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
    - /usr/bin/bash -c 'echo deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/debian/12/amd64/latest bookworm main > /etc/apt/sources.list.d/salt.list'
    - apt update
    - mkdir -p /etc/salt/roles.d
    - mkdir -p /etc/salt/env.d
    - touch /etc/salt/roles.d/master
    - touch /etc/salt/roles.d/consulserver
    - touch /etc/salt/roles.d/consulbootstrapprimary
    - touch /etc/salt/roles.d/natgateway
    - echo ${server_type} > /etc/salt/env.d/server_type
    - mkdir /run/salt-bootstrap
    - wget -O /run/salt-bootstrap/bootstrap-salt.sh https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
    - chown -R salt:salt /etc/salt
    - chmod 700 /run/salt-bootstrap/bootstrap-salt.sh
    - apt -y install --no-install-recommends git
    - /usr/bin/bash /run/salt-bootstrap/bootstrap-salt.sh -r -x python3 -M
    - echo Waiting for key registration...
    - /usr/bin/bash -c 'until [ "/opt/saltstack/salt/salt-key --list=un | grep -q ${hostname}" ]; do sleep 1; echo -n "."; done; echo "";'
    - /opt/saltstack/salt/salt-key --list=un
    - /opt/saltstack/salt/salt-key -y -a ${hostname}


final_message: |
    Next steps:
        - cd /srv
        - git clone -b env/hcloud https://github.com/jdelic/saltshaker
        - /srv/saltshaker/setup_srv_salt.sh
        - salt-call state.highstate
