#!/bin/sh

PATH="/var/qmail/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/daemontools/bin:/usr/local/ucspi-tcp/bin"

if [ ! -d {{pillar['emailstore']['path']}} ]; then
  # disable ourselves, shutdown supervise and remove the symbolic link
  # this can be undone by running /etc/init.d/secure-ok
  cd {{pillar['mail-delivery']['service-link']}}
  rm -f {{pillar['mail-delivery']['service-link']}}
  svc -dx . log
  echo "/secure not available, shutting down mailservices! (delivery)"
  exit 1;
fi

# Using splogger to send the log through syslog.
# Using qmail-local to deliver messages to ~/Mailbox by default.
exec qmail-start ./Maildir/

