# Rights management file for Radicale - A simple calendar server
#
# Section names are used for naming rules and must be unique.
# First rule matching both user and collection patterns will be used.

# Allow reading root collection for authenticated users
[root]
user: .+
collection:
permissions: R

# Allow reading and writing principal collection
# (same as user name)
[principal]
user: .+
collection: {user}
permissions: RW

# Allow reading and writing calendars and address books
# that are direct children of the principal collection
[calendars]
user: .+
collection: {user}/[^/]+
permissions: rw

# Users can read-write to shared calendars belonging to their domain
[domain-wide-access]
user: ^.+@(.+)\..+$
collection: ^shared/{0}/.+$
permission: rw


# This means all users may read and write any collection starting with public.
# We do so by just not testing against the user string.
#[public]
#user: .*
#collection: ^public(/.+)?$
#permission: rw

# The following permissions are recognized:
#
#     R: read collections (excluding address books and calendars)
#     r: read address book and calendar collections
#     i: subset of r that only allows direct access via HTTP method GET (CalDAV/CardDAV is susceptible to expensive search requests)
#     W: write collections (excluding address books and calendars)
#     w: write address book and calendar collections
#     D: allow deleting a collection in case permit_delete_collection=False (>= 3.3.0)
#     d: deny deleting a collection in case permit_delete_collection=True (>= 3.3.0)
#     O: allow overwriting a collection in case permit_overwrite_collection=False
#     o: deny overwriting a collection in case permit_overwrite_collection=True
