include:
    - docker-compose.yml

services:
    any-sync-node-1:
        entrypoint: ["/bin/any-sync-node", "-c", "/etc/any-sync-node/config.yml"]
    any-sync-node-2:
        entrypoint: ["/bin/any-sync-node", "-c", "/etc/any-sync-node/config.yml"]
    any-sync-node-3:
        entrypoint: ["/bin/any-sync-node", "-c", "/etc/any-sync-node/config.yml"]
    any-sync-filenode:
        entrypoint: ["/bin/any-sync-filenode", "-c", "/etc/any-sync-filenode/config.yml"]
    any-sync-coordinator:
        entrypoint: ["/bin/any-sync-coordinator", "-c", "/etc/any-sync-coordinator/config.yml"]
    any-sync-consensusnode:
        # work around https://github.com/anyproto/any-sync-consensusnode/issues/91
        entrypoint: ["/bin/any-sync-consensusnode", "-c", "/etc/any-sync-consensusnode/config.yml"]
    netcheck:
        pull_policy: daily
networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: anytype0
        ipam:
            driver: default
            config:
                - subnet: {{bridge_cidr}}
                  ip_range: {{container_cidr}}
