template {
    source = "/etc/consul/servicerenderer.ctmpl.py"
    destination = "{{servicescript}}"
    command = "{{command}}"
    perms = 0750

    {% if extra_config is defined %}
    {{extra_config}}
    {% endif %}
}
